#!/usr/bin/env python3
"""Run a bounded winedbg loader trace attempt for the VQA sidecar path."""

from __future__ import annotations

import argparse
import csv
import html
import json
import os
import re
import shlex
import shutil
import subprocess
from pathlib import Path


DEFAULT_TRACEPOINTS = Path("output/vqa_runtime_loader_trace_contract/tracepoints.tsv")
DEFAULT_OUTPUT = Path("output/lolg95_winedbg_loader_trace_attempt")

TRACE_FIELDS = [
    "tracepoint_id",
    "breakpoint_va",
    "kind",
    "target",
    "path_pointer",
    "path_ascii",
    "eip",
    "eax",
    "ecx",
    "edx",
    "esi",
    "edi",
    "esp0",
    "esp4",
    "esp8",
    "esp12",
    "esp16",
    "esp20",
    "esp24",
    "capture_note",
]

SUMMARY_FIELDS = [
    "status",
    "session_status",
    "tracepoints",
    "runtime_executable",
    "timeout_seconds",
    "command",
    "returncode",
    "timed_out",
    "xvfb_run",
    "screen",
    "winedbg",
    "wine_renderer",
    "renderer_setup_status",
    "wineprefix",
    "command_file",
    "raw_log",
    "trace",
    "capture_stops",
    "contract_tracepoints",
    "breakpoint_hits",
    "invalid_breakpoints",
    "extracted_rows",
    "createfile_hits",
    "mix_constructor_hits",
    "path_rows",
    "unique_paths",
    "l20_bbi_mentions",
    "l20_bbi_hd_mentions",
    "issues",
    "next_step",
]


def read_csv(path: Path, delimiter: str = ",") -> list[dict[str, str]]:
    if not path.exists():
        return []
    with path.open(newline="", encoding="utf-8") as handle:
        return list(csv.DictReader(handle, delimiter=delimiter))


def write_csv(path: Path, fieldnames: list[str], rows: list[dict[str, str]], delimiter: str = ",") -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames, delimiter=delimiter)
        writer.writeheader()
        writer.writerows(rows)


def compact_text(value: str | bytes | None) -> str:
    if value is None:
        return ""
    if isinstance(value, bytes):
        return value.decode("utf-8", errors="replace")
    return value


def normalize_hex(text: str) -> str:
    value = text.strip().lower()
    if not value:
        return ""
    if value.startswith("0x"):
        return f"0x{int(value, 16) & 0xFFFFFFFF:08x}"
    return f"0x{int(value, 16) & 0xFFFFFFFF:08x}"


def build_command_file(path: Path, tracepoints: list[dict[str, str]], capture_stops: int) -> None:
    lines = [
        "# Generated by tools/run_lolg95_winedbg_loader_trace_attempt.py",
        "# Internal winedbg syntax. Breakpoints are sourced from the loader trace contract.",
    ]
    for row in tracepoints:
        lines.append(f"break *{row['breakpoint_va']}")
    for _index in range(capture_stops):
        lines.extend(
            [
                "cont",
                "info regs",
                "info stack",
                "x /x $esp",
                "x /x ($esp + 4)",
                "x /x ($esp + 8)",
                "x /x ($esp + 12)",
                "x /x ($esp + 16)",
                "x /x ($esp + 20)",
                "x /x ($esp + 24)",
                "x /s $eax",
                "x /s $ecx",
                "x /s $edx",
                "x /s $esi",
                "x /s *$esp",
            ]
        )
    lines.append("quit")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def parse_display_value(line: str) -> tuple[str, str] | None:
    checks = [
        ("$eip", "eip"),
        ("$eax", "eax"),
        ("$ecx", "ecx"),
        ("$edx", "edx"),
        ("$esi", "esi"),
        ("$edi", "edi"),
        ("$esp + 24", "esp24"),
        ("$esp+24", "esp24"),
        ("$esp + 20", "esp20"),
        ("$esp+20", "esp20"),
        ("$esp + 16", "esp16"),
        ("$esp+16", "esp16"),
        ("$esp + 12", "esp12"),
        ("$esp+12", "esp12"),
        ("$esp + 8", "esp8"),
        ("$esp+8", "esp8"),
        ("$esp + 4", "esp4"),
        ("$esp+4", "esp4"),
        ("*$esp", "esp0"),
        ("*($esp)", "esp0"),
    ]
    key = ""
    for marker, candidate in checks:
        if marker in line:
            key = candidate
            break
    if not key:
        return None
    match = re.search(r"(0x[0-9a-fA-F]+|[0-9a-fA-F]{8,16})\s*$", line.strip())
    if not match:
        match = re.search(r"=\s*(0x[0-9a-fA-F]+|[0-9a-fA-F]{8,16})", line)
    if not match:
        return None
    return key, normalize_hex(match.group(1))


def parse_register_values(line: str) -> dict[str, str]:
    values: dict[str, str] = {}
    for source, target in {
        "EIP": "eip",
        "EAX": "eax",
        "ECX": "ecx",
        "EDX": "edx",
        "ESI": "esi",
        "EDI": "edi",
        "ESP": "esp",
    }.items():
        match = re.search(rf"\b{source}:([0-9a-fA-F]{{8,16}})\b", line)
        if match:
            values[target] = normalize_hex(match.group(1))
    return values


def parse_stack_words(line: str) -> list[tuple[str, str]]:
    match = re.search(r"(0x[0-9a-fA-F]+|[0-9a-fA-F]{8,16})\s*:\s*((?:[0-9a-fA-F]{8,16}\s*)+)$", line)
    if not match:
        return []
    base = int(normalize_hex(match.group(1)), 16)
    values = re.findall(r"[0-9a-fA-F]{8,16}", match.group(2))
    return [(f"0x{(base + index * 4) & 0xFFFFFFFF:08x}", normalize_hex(value)) for index, value in enumerate(values)]


def parse_memory_string(line: str) -> tuple[str, str] | None:
    match = re.search(r"(0x[0-9a-fA-F]+|[0-9a-fA-F]{8,16})\s*:\s*\"([^\"]*)\"", line)
    if not match:
        return None
    return normalize_hex(match.group(1)), match.group(2)


def parse_bare_path_string(line: str) -> str:
    value = line.strip()
    if not value or "." not in value:
        return ""
    if re.fullmatch(r"[A-Za-z0-9_./:\\-]+", value):
        return value
    return ""


def assign_stack_word(current: dict[str, str], address: str, value: str) -> bool:
    esp = current.get("esp")
    if not esp:
        return False
    slot = (int(address, 16) - int(esp, 16)) & 0xFFFFFFFF
    if slot in {0, 4, 8, 12, 16, 20, 24}:
        current[f"esp{slot}"] = value
        return True
    return False


def record_path_string(current: dict[str, str], pointer: str, text: str) -> None:
    if current.get("path_ascii"):
        return
    current["path_pointer"] = pointer
    current["path_ascii"] = text


def preferred_path_pointer(current: dict[str, str]) -> str:
    for key in ("esp0", "eax", "edx", "ecx", "esi"):
        value = current.get(key, "")
        if value and int(value, 16) >= 0x10000:
            return value
    return current.get("esp0") or current.get("esi", "")


def extract_trace_rows(raw_log: str, tracepoints: list[dict[str, str]]) -> tuple[list[dict[str, str]], int, int, int]:
    by_breakpoint = {normalize_hex(row["breakpoint_va"]): row for row in tracepoints}
    stop_re = re.compile(r"Stopped on breakpoint\s+\d+\s+at\s+(0x[0-9a-fA-F]+)", re.IGNORECASE)
    invalid_re = re.compile(r"Invalid address\s+\((0x[0-9a-fA-F]+)", re.IGNORECASE)
    rows: list[dict[str, str]] = []
    breakpoint_hits = 0
    invalid_breakpoints = 0
    incomplete_hits = 0
    current: dict[str, str] | None = None

    def flush_current() -> None:
        nonlocal current, incomplete_hits
        if not current:
            return
        required = ("eip", "eax", "ecx", "edx", "esi", "edi")
        complete = all(current.get(field) for field in required)
        if not complete:
            incomplete_hits += 1
        contract = by_breakpoint[current["breakpoint_va"]]
        rows.append(
            {
                "tracepoint_id": contract["tracepoint_id"],
                "breakpoint_va": current["breakpoint_va"],
                "kind": contract["kind"],
                "target": contract["target"],
                "path_pointer": current.get("path_pointer", ""),
                "path_ascii": current.get("path_ascii", ""),
                "eip": current.get("eip", ""),
                "eax": current.get("eax", ""),
                "ecx": current.get("ecx", ""),
                "edx": current.get("edx", ""),
                "esi": current.get("esi", ""),
                "edi": current.get("edi", ""),
                "esp0": current.get("esp0", ""),
                "esp4": current.get("esp4", ""),
                "esp8": current.get("esp8", ""),
                "esp12": current.get("esp12", ""),
                "esp16": current.get("esp16", ""),
                "esp20": current.get("esp20", ""),
                "esp24": current.get("esp24", ""),
                "capture_note": (
                    "winedbg loader trace capture with path string"
                    if current.get("path_ascii")
                    else (
                        "winedbg loader trace capture; path pointer still needs memory-string extraction"
                        if complete
                        else "partial winedbg breakpoint hit; register/stack display was not captured"
                    )
                ),
            }
        )
        current = None

    for line in raw_log.splitlines():
        invalid = invalid_re.search(line)
        if invalid and normalize_hex(invalid.group(1)) in by_breakpoint:
            invalid_breakpoints += 1
        stop = stop_re.search(line)
        if stop:
            flush_current()
            breakpoint_va = normalize_hex(stop.group(1))
            if breakpoint_va in by_breakpoint:
                breakpoint_hits += 1
                current = {"breakpoint_va": breakpoint_va, "eip": breakpoint_va}
            else:
                current = None
            continue
        parsed = parse_display_value(line)
        if parsed and current is not None:
            key, value = parsed
            current[key] = value
            continue
        registers = parse_register_values(line)
        if registers and current is not None:
            current.update(registers)
            continue
        memory_string = parse_memory_string(line)
        if memory_string and current is not None:
            pointer, text = memory_string
            record_path_string(current, pointer, text)
            continue
        bare_path = parse_bare_path_string(line)
        if bare_path and current is not None:
            record_path_string(current, preferred_path_pointer(current), bare_path)
            continue
        for address, value in parse_stack_words(line):
            if current is not None:
                assign_stack_word(current, address, value)
    flush_current()
    return rows, breakpoint_hits, invalid_breakpoints, incomplete_hits


def render_table(rows: list[dict[str, str]], fields: list[str]) -> str:
    head = "".join(f"<th>{html.escape(field)}</th>" for field in fields)
    body = []
    for row in rows:
        body.append("<tr>" + "".join(f"<td>{html.escape(row.get(field, ''))}</td>" for field in fields) + "</tr>")
    return f"<table><thead><tr>{head}</tr></thead><tbody>{''.join(body)}</tbody></table>"


def write_html(path: Path, summary: dict[str, str], trace_rows: list[dict[str, str]]) -> None:
    payload = {"summary": summary, "trace": trace_rows}
    data_json = json.dumps(payload, ensure_ascii=True, separators=(",", ":"))
    page = f"""<!doctype html>
<html lang="fr">
<head>
  <meta charset="utf-8">
  <title>LOLG95 winedbg Loader Trace Attempt</title>
  <style>
    body {{ font-family: system-ui, sans-serif; margin: 24px; background: #f7f7f3; color: #1f2933; }}
    h1, h2 {{ margin-bottom: 0.4rem; }}
    .grid {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(180px, 1fr)); gap: 12px; }}
    .stat {{ background: white; border: 1px solid #d7d7ce; border-radius: 6px; padding: 12px; }}
    .label {{ color: #5f6b76; font-size: 0.85rem; }}
    .value {{ font-size: 1.35rem; font-weight: 700; }}
    table {{ border-collapse: collapse; width: 100%; background: white; margin: 12px 0 24px; }}
    th, td {{ border: 1px solid #d7d7ce; padding: 6px 8px; text-align: left; font-size: 0.86rem; }}
    th {{ background: #ecece4; }}
  </style>
</head>
<body>
  <h1>LOLG95 winedbg Loader Trace Attempt</h1>
  <div class="grid">
    <div class="stat"><div class="label">Statut</div><div class="value">{html.escape(summary['status'])}</div></div>
    <div class="stat"><div class="label">Session</div><div class="value">{html.escape(summary['session_status'])}</div></div>
    <div class="stat"><div class="label">Hits</div><div class="value">{html.escape(summary['breakpoint_hits'])}</div></div>
    <div class="stat"><div class="label">Rows</div><div class="value">{html.escape(summary['extracted_rows'])}</div></div>
  </div>
  <h2>Synthese</h2>
  {render_table([summary], SUMMARY_FIELDS)}
  <h2>Trace</h2>
  {render_table(trace_rows, TRACE_FIELDS)}
  <script type="application/json" id="lolg95-winedbg-loader-trace-attempt">{html.escape(data_json)}</script>
</body>
</html>
"""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(page, encoding="utf-8")


def run_attempt(args: argparse.Namespace) -> tuple[dict[str, str], list[dict[str, str]]]:
    output = args.output
    output.mkdir(parents=True, exist_ok=True)
    command_file = output / "winedbg_commands.txt"
    raw_log = output / "raw.log"
    trace = output / "trace.tsv"
    tracepoints = read_csv(args.tracepoints, delimiter="\t")
    issues: list[str] = []
    if not tracepoints:
        issues.append("missing_tracepoints")
    else:
        build_command_file(command_file, tracepoints, args.capture_stops)

    xvfb_run = args.xvfb_run or shutil.which("xvfb-run") or ""
    winedbg = args.winedbg or shutil.which("winedbg") or ""
    wine = shutil.which("wine") or ""
    runtime_executable = args.runtime_executable
    wineprefix = args.wineprefix or (output / "wineprefix")
    if not xvfb_run:
        issues.append("missing_xvfb_run")
    if not winedbg:
        issues.append("missing_winedbg")
    if not runtime_executable.is_file():
        issues.append("missing_runtime_executable")

    command = [
        xvfb_run or "xvfb-run",
        "-a",
        "-s",
        args.screen,
        winedbg or "winedbg",
        "--file",
        str(command_file),
        str(runtime_executable),
    ]
    session_status = "dry_run" if args.dry_run else "not_started"
    returncode = ""
    timed_out = "0"
    stdout_text = ""
    stderr_text = ""
    renderer_setup_status = ""
    if args.dry_run:
        raw_log.write_text("", encoding="utf-8")
    elif not any(issue in issues for issue in ("missing_tracepoints", "missing_xvfb_run", "missing_winedbg", "missing_runtime_executable")):
        env = os.environ.copy()
        env["WINEPREFIX"] = str(wineprefix.resolve())
        if args.wine_renderer:
            if not wine:
                renderer_setup_status = "missing_wine"
                issues.append(renderer_setup_status)
            else:
                renderer = subprocess.run(
                    [
                        wine,
                        "reg",
                        "add",
                        r"HKCU\Software\Wine\Direct3D",
                        "/v",
                        "renderer",
                        "/d",
                        args.wine_renderer,
                        "/f",
                    ],
                    stdout=subprocess.PIPE,
                    stderr=subprocess.PIPE,
                    text=True,
                    errors="replace",
                    check=False,
                    timeout=30,
                    env=env,
                )
                renderer_setup_status = f"exited_{renderer.returncode}"
                if renderer.returncode != 0:
                    issues.append(f"renderer_setup_failed:{renderer.returncode}")
        try:
            result = subprocess.run(
                command,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                text=True,
                errors="replace",
                check=False,
                timeout=args.timeout,
                env=env,
            )
            returncode = str(result.returncode)
            session_status = "exited_0" if result.returncode == 0 else f"exited_{result.returncode}"
            stdout_text = result.stdout
            stderr_text = result.stderr
        except subprocess.TimeoutExpired as exc:
            timed_out = "1"
            session_status = "started_timeout"
            stdout_text = compact_text(exc.stdout)
            stderr_text = compact_text(exc.stderr)
        except OSError as exc:
            session_status = f"launch_error:{type(exc).__name__}"
            issues.append(session_status)
            stderr_text = str(exc)
        raw_log.write_text(stdout_text + stderr_text, encoding="utf-8", errors="replace")

    raw_text = raw_log.read_text(encoding="utf-8", errors="replace")
    trace_rows, breakpoint_hits, invalid_breakpoints, incomplete_hits = extract_trace_rows(raw_text, tracepoints)
    write_csv(trace, TRACE_FIELDS, trace_rows, delimiter="\t")
    if incomplete_hits:
        issues.append(f"incomplete_breakpoint_hits:{incomplete_hits}")
    if invalid_breakpoints:
        issues.append(f"invalid_breakpoints:{invalid_breakpoints}")
    if breakpoint_hits == 0 and not args.dry_run:
        issues.append("no_contract_breakpoint_hits")
    if not trace_rows and not args.dry_run:
        issues.append("no_trace_rows")

    createfile_hits = sum(1 for row in trace_rows if row.get("kind") == "createfile")
    mix_constructor_hits = sum(1 for row in trace_rows if row.get("kind") == "mix_constructor")
    captured_paths = [row.get("path_ascii", "") for row in trace_rows if row.get("path_ascii", "")]
    raw_upper = raw_text.upper()
    l20_bbi_mentions = raw_upper.count("L20_BBI")
    l20_bbi_hd_mentions = raw_upper.count("L20_BBI_HD")
    if l20_bbi_hd_mentions:
        status = "pass"
        next_step = "confirm that sidecar payload IDs are read from L20_BBI_HD.MIX"
    elif trace_rows and incomplete_hits:
        status = "gap"
        next_step = "adjust winedbg capture commands to record registers/stack at the hit breakpoint, then extract path strings"
    elif any(row.get("path_ascii") for row in trace_rows):
        status = "gap"
        next_step = "continue the loader trace beyond the captured startup file opens until L20_BBI.MIX is observed"
    elif trace_rows:
        status = "gap"
        next_step = "extract path strings from captured pointers and add the L20_BBI_HD.MIX fallback hook"
    else:
        status = "gap"
        next_step = "exercise startup/gameplay far enough to hit the loader tracepoints or adjust breakpoint timing"

    summary = {
        "status": status,
        "session_status": session_status,
        "tracepoints": str(args.tracepoints),
        "runtime_executable": str(runtime_executable),
        "timeout_seconds": str(args.timeout),
        "command": shlex.join(command),
        "returncode": returncode,
        "timed_out": timed_out,
        "xvfb_run": xvfb_run,
        "screen": args.screen,
        "winedbg": winedbg,
        "wine_renderer": args.wine_renderer,
        "renderer_setup_status": renderer_setup_status,
        "wineprefix": str(wineprefix),
        "command_file": str(command_file),
        "raw_log": str(raw_log),
        "trace": str(trace),
        "capture_stops": str(args.capture_stops),
        "contract_tracepoints": str(len(tracepoints)),
        "breakpoint_hits": str(breakpoint_hits),
        "invalid_breakpoints": str(invalid_breakpoints),
        "extracted_rows": str(len(trace_rows)),
        "createfile_hits": str(createfile_hits),
        "mix_constructor_hits": str(mix_constructor_hits),
        "path_rows": str(len(captured_paths)),
        "unique_paths": str(len({path.lower() for path in captured_paths})),
        "l20_bbi_mentions": str(l20_bbi_mentions),
        "l20_bbi_hd_mentions": str(l20_bbi_hd_mentions),
        "issues": ";".join(dict.fromkeys(issues)),
        "next_step": next_step,
    }
    return summary, trace_rows


def main() -> None:
    parser = argparse.ArgumentParser(description="Run a bounded winedbg loader trace attempt for LOLG95.EXE.")
    parser.add_argument("--tracepoints", type=Path, default=DEFAULT_TRACEPOINTS)
    parser.add_argument("-o", "--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--runtime-executable", type=Path, default=Path("LOLG95.EXE"))
    parser.add_argument("--xvfb-run", default="")
    parser.add_argument("--winedbg", default="")
    parser.add_argument("--wine-renderer", default="")
    parser.add_argument("--wineprefix", type=Path)
    parser.add_argument("--screen", default="-screen 0 640x480x16")
    parser.add_argument("--timeout", type=int, default=45)
    parser.add_argument("--capture-stops", type=int, default=256)
    parser.add_argument("--cont-count", type=int, default=2000, help=argparse.SUPPRESS)
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--fail-on-gaps", action="store_true")
    args = parser.parse_args()

    summary, trace_rows = run_attempt(args)
    args.output.mkdir(parents=True, exist_ok=True)
    write_csv(args.output / "summary.csv", SUMMARY_FIELDS, [summary])
    write_html(args.output / "index.html", summary, trace_rows)
    print(f"LOLG95 winedbg loader trace attempt: {summary['status']} ({summary['session_status']})")
    print(f"Summary: {args.output / 'summary.csv'}")
    print(f"Trace rows: {summary['extracted_rows']} / hits: {summary['breakpoint_hits']}")
    if args.fail_on_gaps and summary["status"] != "pass":
        raise SystemExit(1)


if __name__ == "__main__":
    main()
