#!/usr/bin/env python3
"""Trace LOLG95 MIX entry lookup hits in a visible Wine process."""

from __future__ import annotations

import argparse
import csv
import os
import re
import shlex
import shutil
import subprocess
import sys
import time
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from run_lolg95_winedbg_attach_pilot_attempt import (  # noqa: E402
    parse_lolg95_linux_pid,
    parse_lolg95_pid,
    run_with_timeout,
    stop_process,
    write_process_dwords,
)
from run_lolg95_winedbg_loader_trace_attempt import compact_text, read_csv, write_csv  # noqa: E402


DEFAULT_OUTPUT = Path("output/lolg95_winedbg_mix_lookup_l20_additive_attempt")
DEFAULT_EXPECTED_IDS = Path("output/vqa_runtime_loader_trace_contract/expected_sidecar_ids.csv")
LOOKUP_HIT_VA = 0x004E3D18

TRACE_FIELDS = [
    "row_index",
    "breakpoint_va",
    "entry_id",
    "entry_offset",
    "entry_size",
    "expected_source_size",
    "expected_sidecar_size",
    "target_status",
    "archive_object",
    "archive_name_pointer",
    "archive_hint",
    "eax",
    "ebx",
    "ecx",
    "edx",
    "esi",
    "edi",
    "esp",
]

SUMMARY_FIELDS = [
    "status",
    "session_status",
    "expected_ids",
    "runtime_executable",
    "runtime_args",
    "wineprefix",
    "wine_desktop",
    "startup_wait_seconds",
    "attach_pid",
    "linux_pid",
    "force_level_index",
    "force_level_slot",
    "force_level_write_status",
    "force_level_write_log",
    "command",
    "winedbg_command",
    "winedbg_returncode",
    "winedbg_timed_out",
    "xdotool_command",
    "xdotool_status",
    "pilot_keys",
    "pilot_key_status",
    "command_file",
    "info_proc_log",
    "raw_log",
    "trace",
    "capture_stops",
    "breakpoint_hits",
    "extracted_rows",
    "unique_entry_ids",
    "target_hits",
    "target_ids_seen",
    "target_sidecar_hits",
    "target_sidecar_ids_seen",
    "target_base_hits",
    "target_base_ids_seen",
    "target_unknown_hits",
    "missing_target_ids",
    "issues",
    "next_step",
]


def hex32(value: int) -> str:
    return f"{value & 0xFFFFFFFF:08x}"


def parse_hex(text: str) -> int:
    value = text.strip().lower()
    if value.startswith("0x"):
        return int(value, 16)
    return int(value, 16)


def load_expected(path: Path) -> dict[str, dict[str, str]]:
    rows = read_csv(path)
    expected: dict[str, dict[str, str]] = {}
    for row in rows:
        file_id = row.get("file_id", "").lower()
        if not file_id:
            continue
        expected[file_id] = {
            "source_size": row.get("source_size", ""),
            "sidecar_size": row.get("sidecar_size", ""),
            "source_archive": row.get("source_archive", ""),
            "sidecar_archive": row.get("sidecar_archive", ""),
        }
    return expected


def build_lookup_command_file(path: Path, attach_pid: str, capture_stops: int) -> None:
    lines = [
        "# Generated by tools/run_lolg95_winedbg_mix_lookup_trace_attempt.py",
        f"attach 0x{attach_pid}",
        f"break *0x{LOOKUP_HIT_VA:08x}",
    ]
    for _index in range(capture_stops):
        lines.extend(
            [
                "cont",
                "info regs",
                "info stack",
                "x /x $esp",
                "x /x $edx",
                "x /x ($edx + 4)",
                "x /x ($edx + 8)",
                "x /x $ebx",
                "x /x ($ebx + 8)",
                "x /s *($ebx + 8)",
            ]
        )
    lines.append("quit")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def parse_registers(block: str) -> dict[str, str]:
    registers: dict[str, str] = {}
    for source, target in {
        "EAX": "eax",
        "EBX": "ebx",
        "ECX": "ecx",
        "EDX": "edx",
        "ESI": "esi",
        "EDI": "edi",
        "ESP": "esp",
    }.items():
        match = re.search(rf"\b{source}:([0-9a-fA-F]{{8,16}})\b", block)
        if match:
            registers[target] = f"0x{parse_hex(match.group(1)) & 0xFFFFFFFF:08x}"
    return registers


def parse_archive_hint(block: str) -> str:
    for line in block.splitlines():
        value = line.strip()
        if ".MIX" in value.upper() and re.fullmatch(r"[A-Za-z0-9_./:\\-]+", value):
            return value
    return ""


def classify_target(entry_id: str, entry_size: str, expected: dict[str, dict[str, str]]) -> tuple[str, str, str]:
    row = expected.get(entry_id)
    if not row:
        return "not_target", "", ""
    source_size = row["source_size"]
    sidecar_size = row["sidecar_size"]
    if entry_size == sidecar_size:
        return "sidecar", source_size, sidecar_size
    if entry_size == source_size:
        return "base", source_size, sidecar_size
    return "target_unknown_size", source_size, sidecar_size


def extract_lookup_rows(raw_text: str, expected: dict[str, dict[str, str]]) -> tuple[list[dict[str, str]], int]:
    stop_re = re.compile(r"Stopped on breakpoint\s+\d+\s+at\s+(0x[0-9a-fA-F]+)", re.IGNORECASE)
    matches = list(stop_re.finditer(raw_text))
    rows: list[dict[str, str]] = []
    breakpoint_hits = 0
    for index, match in enumerate(matches):
        breakpoint_va = f"0x{parse_hex(match.group(1)) & 0xFFFFFFFF:08x}"
        block_end = matches[index + 1].start() if index + 1 < len(matches) else len(raw_text)
        block = raw_text[match.start() : block_end]
        if parse_hex(breakpoint_va) != LOOKUP_HIT_VA:
            continue
        breakpoint_hits += 1
        registers = parse_registers(block)
        values = re.findall(r"^\s*([0-9a-fA-F]{8})\s*$", block, flags=re.MULTILINE)
        if len(values) < 6:
            continue
        entry_id = values[1].lower()
        entry_offset = str(parse_hex(values[2]))
        entry_size = str(parse_hex(values[3]))
        status, source_size, sidecar_size = classify_target(entry_id, entry_size, expected)
        rows.append(
            {
                "row_index": str(len(rows)),
                "breakpoint_va": breakpoint_va,
                "entry_id": entry_id,
                "entry_offset": entry_offset,
                "entry_size": entry_size,
                "expected_source_size": source_size,
                "expected_sidecar_size": sidecar_size,
                "target_status": status,
                "archive_object": registers.get("ebx", ""),
                "archive_name_pointer": f"0x{parse_hex(values[5]) & 0xFFFFFFFF:08x}",
                "archive_hint": parse_archive_hint(block),
                "eax": registers.get("eax", ""),
                "ebx": registers.get("ebx", ""),
                "ecx": registers.get("ecx", ""),
                "edx": registers.get("edx", ""),
                "esi": registers.get("esi", ""),
                "edi": registers.get("edi", ""),
                "esp": registers.get("esp", ""),
            }
        )
    return rows, breakpoint_hits


def run_attempt(args: argparse.Namespace) -> dict[str, str]:
    output = args.output.resolve()
    output.mkdir(parents=True, exist_ok=True)
    info_proc_log = output / "info_proc.log"
    raw_log = output / "raw.log"
    trace_path = output / "trace.tsv"
    command_file = output / "winedbg_lookup_commands.txt"
    xdotool_log = output / "xdotool.log"
    pilot_key_log = output / "pilot_keys.log"
    ps_log = output / "ps.txt"
    force_level_log = output / "force_level_write.log"
    game_stdout = output / "game.out"
    game_stderr = output / "game.err"

    expected = load_expected(args.expected_ids)
    expected_ids = sorted(expected)
    issues: list[str] = []
    if not expected:
        issues.append("missing_expected_ids")

    wine = args.wine or shutil.which("wine") or ""
    winedbg = args.winedbg or shutil.which("winedbg") or ""
    xdotool = args.xdotool or shutil.which("xdotool") or ""
    if not wine:
        issues.append("missing_wine")
    if not winedbg:
        issues.append("missing_winedbg")
    if not args.runtime_executable.is_file():
        issues.append("missing_runtime_executable")
    if args.click and not xdotool:
        issues.append("missing_xdotool")

    env = os.environ.copy()
    env["WINEPREFIX"] = str(args.wineprefix.resolve())
    env["WINEDEBUG"] = args.winedebug
    if args.xdotool_library_path:
        env["LD_LIBRARY_PATH"] = (
            args.xdotool_library_path
            if not env.get("LD_LIBRARY_PATH")
            else f"{args.xdotool_library_path}:{env['LD_LIBRARY_PATH']}"
        )

    runtime_args = args.runtime_arg or ["-CD", r"D:\WESTWOOD\LOLG"]
    game_command = [
        wine or "wine",
        "explorer",
        f"/desktop={args.wine_desktop}",
        str(args.runtime_executable),
        *runtime_args,
    ]
    session_status = "not_started"
    attach_pid = ""
    linux_pid = ""
    force_level_write_status = ""
    xdotool_status = ""
    pilot_key_status = ""
    winedbg_returncode = ""
    winedbg_timed_out = "0"
    game_process: subprocess.Popen[str] | None = None

    if any(issue.startswith("missing_") for issue in issues):
        raw_log.write_text("", encoding="utf-8")
        info_proc_log.write_text("", encoding="utf-8")
    else:
        try:
            with game_stdout.open("w", encoding="utf-8", errors="replace") as stdout_handle, game_stderr.open(
                "w", encoding="utf-8", errors="replace"
            ) as stderr_handle:
                game_process = subprocess.Popen(
                    game_command,
                    stdout=stdout_handle,
                    stderr=stderr_handle,
                    text=True,
                    env=env,
                    cwd=args.cwd,
                )
            time.sleep(args.startup_wait)

            info_stdout, info_stderr, _info_returncode, _info_timeout = run_with_timeout(
                [winedbg or "winedbg", "--command", "info proc"],
                args.info_timeout,
                env,
                args.cwd,
            )
            info_proc_text = info_stdout + info_stderr
            info_proc_log.write_text(info_proc_text, encoding="utf-8", errors="replace")
            attach_pid = parse_lolg95_pid(info_proc_text, args.runtime_executable.name)

            if args.force_level_index is not None or args.force_level_slot is not None:
                ps_stdout, ps_stderr, _ps_returncode, _ps_timeout = run_with_timeout(
                    ["ps", "-eo", "pid=,comm=,args="],
                    8,
                    env,
                    args.cwd,
                )
                ps_text = ps_stdout + ps_stderr
                ps_log.write_text(ps_text, encoding="utf-8", errors="replace")
                linux_pid = parse_lolg95_linux_pid(ps_text, args.runtime_executable.name)
                if not linux_pid:
                    force_level_write_status = "missing_linux_pid"
                    issues.append("missing_lolg95_linux_process")
                    force_level_log.write_text("", encoding="utf-8")
                else:
                    writes = []
                    if args.force_level_index is not None:
                        writes.append((0x005B0948, args.force_level_index))
                    if args.force_level_slot is not None:
                        writes.append((0x005B094C, args.force_level_slot))
                    force_log_text, force_issues = write_process_dwords(linux_pid, writes)
                    force_level_log.write_text(force_log_text, encoding="utf-8", errors="replace")
                    if force_issues:
                        force_level_write_status = "failed"
                        issues.extend(force_issues)
                    else:
                        force_level_write_status = "pass"

            if not attach_pid:
                issues.append("missing_lolg95_process")
                raw_log.write_text("", encoding="utf-8")
            else:
                build_lookup_command_file(command_file, attach_pid, args.capture_stops)
                winedbg_command = [winedbg or "winedbg", "--file", str(command_file)]
                with raw_log.open("w", encoding="utf-8", errors="replace") as raw_handle:
                    debugger = subprocess.Popen(
                        winedbg_command,
                        stdout=raw_handle,
                        stderr=subprocess.STDOUT,
                        text=True,
                        env=env,
                        cwd=args.cwd,
                    )
                    time.sleep(args.click_delay)
                    if args.click:
                        click_command = [
                            xdotool or "xdotool",
                            "search",
                            "--name",
                            args.click_window_name,
                            "mousemove",
                            "--window",
                            "%@",
                            str(args.click_x),
                            str(args.click_y),
                            "click",
                            "1",
                        ]
                        click_results = []
                        for _index in range(args.click_count):
                            click_stdout, click_stderr, click_returncode, click_timeout = run_with_timeout(
                                click_command,
                                args.click_timeout,
                                env,
                                args.cwd,
                            )
                            click_results.append(
                                f"returncode={click_returncode or 'timeout'} timeout={click_timeout}\n"
                                f"{click_stdout}{click_stderr}"
                            )
                            if args.click_interval:
                                time.sleep(args.click_interval)
                        xdotool_log.write_text("\n--- click ---\n".join(click_results), encoding="utf-8")
                        xdotool_status = ";".join(line.splitlines()[0] for line in click_results)
                    if args.pilot_key and xdotool:
                        key_results = []
                        for key_name in args.pilot_key:
                            if args.pilot_key_delay:
                                time.sleep(args.pilot_key_delay)
                            key_command = [
                                xdotool,
                                "search",
                                "--name",
                                args.click_window_name,
                                "key",
                                "--window",
                                "%@",
                                key_name,
                            ]
                            key_stdout, key_stderr, key_returncode, key_timeout = run_with_timeout(
                                key_command,
                                args.click_timeout,
                                env,
                                args.cwd,
                            )
                            key_results.append(
                                f"key={key_name} returncode={key_returncode or 'timeout'} timeout={key_timeout}\n"
                                f"{key_stdout}{key_stderr}"
                            )
                        pilot_key_log.write_text("\n--- key ---\n".join(key_results), encoding="utf-8")
                        pilot_key_status = ";".join(line.splitlines()[0] for line in key_results)
                    try:
                        winedbg_returncode = str(debugger.wait(timeout=args.attach_timeout))
                        session_status = "exited_0" if winedbg_returncode == "0" else f"exited_{winedbg_returncode}"
                    except subprocess.TimeoutExpired:
                        winedbg_timed_out = "1"
                        session_status = "started_timeout"
                        debugger.kill()
                        debugger.wait(timeout=8)
        finally:
            stop_process(game_process)

    raw_text = raw_log.read_text(encoding="utf-8", errors="replace") if raw_log.exists() else ""
    trace_rows, breakpoint_hits = extract_lookup_rows(raw_text, expected)
    write_csv(trace_path, TRACE_FIELDS, trace_rows, delimiter="\t")
    if breakpoint_hits == 0:
        issues.append("no_lookup_hit_breakpoints")
    if not trace_rows:
        issues.append("no_lookup_trace_rows")

    target_rows = [row for row in trace_rows if row["target_status"] != "not_target"]
    sidecar_rows = [row for row in target_rows if row["target_status"] == "sidecar"]
    base_rows = [row for row in target_rows if row["target_status"] == "base"]
    unknown_rows = [row for row in target_rows if row["target_status"] == "target_unknown_size"]
    target_ids_seen = sorted({row["entry_id"] for row in target_rows})
    sidecar_ids_seen = sorted({row["entry_id"] for row in sidecar_rows})
    base_ids_seen = sorted({row["entry_id"] for row in base_rows})
    missing_target_ids = [file_id for file_id in expected_ids if file_id not in set(target_ids_seen)]

    if len(sidecar_ids_seen) == len(expected_ids):
        status = "pass"
        next_step = "convert the additive probe into a stable runtime fallback after documenting all target IDs as sidecar hits"
    elif sidecar_ids_seen:
        status = "gap"
        next_step = "drive gameplay or force entry requests further until all deferred IDs are observed from the sidecar"
    elif target_rows:
        status = "gap"
        next_step = "adjust archive order or lookup fallback because target IDs still resolve from the base archive"
    else:
        status = "gap"
        next_step = "capture deeper gameplay or add a targeted entry-request probe because the 8 deferred IDs were not requested"

    summary = {
        "status": status,
        "session_status": session_status,
        "expected_ids": str(len(expected_ids)),
        "runtime_executable": str(args.runtime_executable),
        "runtime_args": shlex.join(runtime_args),
        "wineprefix": str(args.wineprefix),
        "wine_desktop": args.wine_desktop,
        "startup_wait_seconds": str(args.startup_wait),
        "attach_pid": attach_pid,
        "linux_pid": linux_pid,
        "force_level_index": "" if args.force_level_index is None else str(args.force_level_index),
        "force_level_slot": "" if args.force_level_slot is None else str(args.force_level_slot),
        "force_level_write_status": force_level_write_status,
        "force_level_write_log": str(force_level_log) if force_level_write_status else "",
        "command": shlex.join(game_command),
        "winedbg_command": shlex.join([winedbg or "winedbg", "--file", str(command_file)]),
        "winedbg_returncode": winedbg_returncode,
        "winedbg_timed_out": winedbg_timed_out,
        "xdotool_command": (
            shlex.join(
                [
                    xdotool or "xdotool",
                    "search",
                    "--name",
                    args.click_window_name,
                    "mousemove",
                    "--window",
                    "%@",
                    str(args.click_x),
                    str(args.click_y),
                    "click",
                    "1",
                ]
            )
            if args.click
            else ""
        ),
        "xdotool_status": xdotool_status,
        "pilot_keys": " ".join(args.pilot_key),
        "pilot_key_status": pilot_key_status,
        "command_file": str(command_file),
        "info_proc_log": str(info_proc_log),
        "raw_log": str(raw_log),
        "trace": str(trace_path),
        "capture_stops": str(args.capture_stops),
        "breakpoint_hits": str(breakpoint_hits),
        "extracted_rows": str(len(trace_rows)),
        "unique_entry_ids": str(len({row["entry_id"] for row in trace_rows})),
        "target_hits": str(len(target_rows)),
        "target_ids_seen": ",".join(target_ids_seen),
        "target_sidecar_hits": str(len(sidecar_rows)),
        "target_sidecar_ids_seen": ",".join(sidecar_ids_seen),
        "target_base_hits": str(len(base_rows)),
        "target_base_ids_seen": ",".join(base_ids_seen),
        "target_unknown_hits": str(len(unknown_rows)),
        "missing_target_ids": ",".join(missing_target_ids),
        "issues": ";".join(dict.fromkeys(issues)),
        "next_step": next_step,
    }
    write_csv(output / "summary.csv", SUMMARY_FIELDS, [summary])
    return summary


def main() -> None:
    parser = argparse.ArgumentParser(description="Trace LOLG95 MIX lookup hits under Wine/winedbg.")
    parser.add_argument("-o", "--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--expected-ids", type=Path, default=DEFAULT_EXPECTED_IDS)
    parser.add_argument("--runtime-executable", type=Path, default=Path("LOLG95.EXE"))
    parser.add_argument("--runtime-arg", action="append", default=[])
    parser.add_argument("--cwd", type=Path, default=Path.cwd())
    parser.add_argument("--wineprefix", type=Path, required=True)
    parser.add_argument("--wine", default="")
    parser.add_argument("--winedbg", default="")
    parser.add_argument("--winedebug", default="-all")
    parser.add_argument("--wine-desktop", default="LOLG,1280x1024")
    parser.add_argument("--startup-wait", type=int, default=35)
    parser.add_argument("--info-timeout", type=int, default=12)
    parser.add_argument("--attach-timeout", type=int, default=120)
    parser.add_argument("--capture-stops", type=int, default=512)
    parser.add_argument("--xdotool", default="/tmp/xdotool-local/usr/bin/xdotool")
    parser.add_argument("--xdotool-library-path", default="/tmp/xdotool-local/usr/lib/x86_64-linux-gnu")
    parser.add_argument("--click", action=argparse.BooleanOptionalAction, default=True)
    parser.add_argument("--click-window-name", default="Lands Of Lore Guardians")
    parser.add_argument("--click-x", type=int, default=95)
    parser.add_argument("--click-y", type=int, default=116)
    parser.add_argument("--click-delay", type=int, default=6)
    parser.add_argument("--click-timeout", type=int, default=8)
    parser.add_argument("--click-count", type=int, default=2)
    parser.add_argument("--click-interval", type=float, default=2.0)
    parser.add_argument("--pilot-key", action="append", default=[])
    parser.add_argument("--pilot-key-delay", type=float, default=8.0)
    parser.add_argument("--force-level-index", type=lambda value: int(value, 0))
    parser.add_argument("--force-level-slot", type=lambda value: int(value, 0))
    args = parser.parse_args()

    summary = run_attempt(args)
    print(f"LOLG95 MIX lookup trace: {summary['status']} ({summary['session_status']})")
    print(f"Summary: {args.output / 'summary.csv'}")
    print(f"Trace rows: {summary['extracted_rows']} / hits: {summary['breakpoint_hits']}")
    print(f"Target sidecar IDs: {summary['target_sidecar_ids_seen'] or '-'}")


if __name__ == "__main__":
    main()
