#!/usr/bin/env python3
"""Run a bounded attached winedbg trace against the visible LOLG95 Wine process."""

from __future__ import annotations

import argparse
import csv
import os
import re
import shlex
import shutil
import struct
import subprocess
import sys
import time
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from run_lolg95_winedbg_loader_trace_attempt import (  # noqa: E402
    TRACE_FIELDS,
    compact_text,
    extract_trace_rows,
    read_csv,
    write_csv,
)


DEFAULT_TRACEPOINTS = Path("output/vqa_runtime_loader_trace_contract/tracepoints.tsv")
DEFAULT_OUTPUT = Path("output/lolg95_winedbg_attach_pilot_attempt")

SUMMARY_FIELDS = [
    "status",
    "session_status",
    "tracepoints",
    "runtime_executable",
    "runtime_args",
    "wineprefix",
    "wine_desktop",
    "startup_wait_seconds",
    "attach_pid",
    "linux_pid",
    "force_level_index",
    "force_level_slot",
    "force_level_write_status",
    "force_level_write_log",
    "command",
    "winedbg_command",
    "winedbg_returncode",
    "winedbg_timed_out",
    "xdotool_command",
    "xdotool_status",
    "pilot_keys",
    "pilot_key_status",
    "command_file",
    "info_proc_log",
    "raw_log",
    "trace",
    "capture_stops",
    "contract_tracepoints",
    "breakpoint_hits",
    "invalid_breakpoints",
    "extracted_rows",
    "createfile_hits",
    "mix_constructor_hits",
    "path_rows",
    "unique_paths",
    "l20_bbi_mentions",
    "l20_bbi_hd_mentions",
    "issues",
    "next_step",
]


def build_attach_command_file(
    path: Path,
    attach_pid: str,
    tracepoints: list[dict[str, str]],
    capture_stops: int,
) -> None:
    lines = [
        "# Generated by tools/run_lolg95_winedbg_attach_pilot_attempt.py",
        f"attach 0x{attach_pid}",
    ]
    for row in tracepoints:
        lines.append(f"break *{row['breakpoint_va']}")
    for _index in range(capture_stops):
        lines.extend(
            [
                "cont",
                "info regs",
                "info stack",
                "x /x $esp",
                "x /x ($esp + 4)",
                "x /x ($esp + 8)",
                "x /x ($esp + 12)",
                "x /x ($esp + 16)",
                "x /x ($esp + 20)",
                "x /x ($esp + 24)",
                "x /s $eax",
                "x /s $ecx",
                "x /s $edx",
                "x /s $esi",
                "x /s *$esp",
            ]
        )
    lines.append("quit")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def parse_lolg95_pid(info_proc_text: str, executable_name: str = "LOLG95.EXE") -> str:
    target = re.escape(executable_name)
    for line in info_proc_text.splitlines():
        match = re.search(rf"^\s*=?([0-9a-fA-F]{{8}})\s+\d+\s+.*'{target}'", line, re.IGNORECASE)
        if match:
            return match.group(1).lower()
    return ""


def parse_lolg95_linux_pid(ps_text: str, executable_name: str) -> str:
    target = executable_name.lower()
    found = ""
    for line in ps_text.splitlines():
        parts = line.split(None, 2)
        command = parts[1].lower() if len(parts) >= 2 else ""
        args = parts[2].lower() if len(parts) >= 3 else ""
        if command == target:
            found = parts[0]
            continue
        if command not in {"wine", "wine-preloader", "wine64", "wine64-preloader"}:
            continue
        normalized_args = args.replace("\\", "/")
        if any(token.strip("'\"").endswith("/" + target) or token.strip("'\"") == target for token in normalized_args.split()):
            found = parts[0]
    return found


def write_process_dwords(pid: str, writes: list[tuple[int, int]]) -> tuple[str, list[str]]:
    rows: list[str] = []
    issues: list[str] = []
    try:
        with open(f"/proc/{int(pid)}/mem", "r+b", buffering=0) as handle:
            for address, value in writes:
                handle.seek(address)
                before = handle.read(4)
                handle.seek(address)
                handle.write(struct.pack("<I", value & 0xFFFFFFFF))
                handle.seek(address)
                after = handle.read(4)
                rows.append(f"{address:#010x}\tbefore={before.hex()}\tafter={after.hex()}\tvalue={value:#010x}")
                if after != struct.pack("<I", value & 0xFFFFFFFF):
                    issues.append(f"write_mismatch:{address:#010x}")
    except OSError as exc:
        issues.append(f"proc_mem_error:{type(exc).__name__}:{exc}")
    except ValueError as exc:
        issues.append(f"invalid_linux_pid:{exc}")
    return "\n".join(rows) + ("\n" if rows else ""), issues


def run_with_timeout(
    command: list[str],
    timeout: int,
    env: dict[str, str],
    cwd: Path,
) -> tuple[str, str, str, str]:
    try:
        result = subprocess.run(
            command,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
            errors="replace",
            check=False,
            timeout=timeout,
            env=env,
            cwd=cwd,
        )
        return compact_text(result.stdout), compact_text(result.stderr), str(result.returncode), "0"
    except subprocess.TimeoutExpired as exc:
        return compact_text(exc.stdout), compact_text(exc.stderr), "", "1"


def stop_process(process: subprocess.Popen[str] | None) -> None:
    if process is None or process.poll() is not None:
        return
    process.terminate()
    try:
        process.wait(timeout=8)
    except subprocess.TimeoutExpired:
        process.kill()
        process.wait(timeout=8)


def run_attempt(args: argparse.Namespace) -> dict[str, str]:
    output = args.output.resolve()
    output.mkdir(parents=True, exist_ok=True)
    info_proc_log = output / "info_proc.log"
    raw_log = output / "raw.log"
    trace_path = output / "trace.tsv"
    command_file = output / "winedbg_attach_commands.txt"
    xwininfo_log = output / "xwininfo.txt"
    xdotool_log = output / "xdotool.log"
    pilot_key_log = output / "pilot_keys.log"
    ps_log = output / "ps.txt"
    force_level_log = output / "force_level_write.log"
    game_stdout = output / "game.out"
    game_stderr = output / "game.err"

    tracepoints = read_csv(args.tracepoints, delimiter="\t")
    issues: list[str] = []
    if not tracepoints:
        issues.append("missing_tracepoints")

    wine = args.wine or shutil.which("wine") or ""
    winedbg = args.winedbg or shutil.which("winedbg") or ""
    xwininfo = args.xwininfo or shutil.which("xwininfo") or ""
    xdotool = args.xdotool or shutil.which("xdotool") or ""
    if not wine:
        issues.append("missing_wine")
    if not winedbg:
        issues.append("missing_winedbg")
    if not args.runtime_executable.is_file():
        issues.append("missing_runtime_executable")
    if args.click and not xdotool:
        issues.append("missing_xdotool")

    env = os.environ.copy()
    env["WINEPREFIX"] = str(args.wineprefix.resolve())
    env["WINEDEBUG"] = args.winedebug
    if args.xdotool_library_path:
        env["LD_LIBRARY_PATH"] = (
            args.xdotool_library_path
            if not env.get("LD_LIBRARY_PATH")
            else f"{args.xdotool_library_path}:{env['LD_LIBRARY_PATH']}"
        )

    runtime_args = args.runtime_arg or ["-CD", r"D:\WESTWOOD\LOLG"]
    game_command = [
        wine or "wine",
        "explorer",
        f"/desktop={args.wine_desktop}",
        str(args.runtime_executable),
        *runtime_args,
    ]
    session_status = "not_started"
    attach_pid = ""
    linux_pid = ""
    force_level_write_status = ""
    xdotool_status = ""
    pilot_key_status = ""
    winedbg_returncode = ""
    winedbg_timed_out = "0"
    game_process: subprocess.Popen[str] | None = None

    if any(issue.startswith("missing_") for issue in issues):
        raw_log.write_text("", encoding="utf-8")
        info_proc_log.write_text("", encoding="utf-8")
    else:
        try:
            with game_stdout.open("w", encoding="utf-8", errors="replace") as stdout_handle, game_stderr.open(
                "w", encoding="utf-8", errors="replace"
            ) as stderr_handle:
                game_process = subprocess.Popen(
                    game_command,
                    stdout=stdout_handle,
                    stderr=stderr_handle,
                    text=True,
                    env=env,
                    cwd=args.cwd,
                )
            time.sleep(args.startup_wait)

            info_stdout, info_stderr, _info_returncode, _info_timeout = run_with_timeout(
                [winedbg or "winedbg", "--command", "info proc"],
                args.info_timeout,
                env,
                args.cwd,
            )
            info_proc_text = info_stdout + info_stderr
            info_proc_log.write_text(info_proc_text, encoding="utf-8", errors="replace")
            attach_pid = parse_lolg95_pid(info_proc_text, args.runtime_executable.name)
            if args.force_level_index is not None or args.force_level_slot is not None:
                ps_stdout, ps_stderr, _ps_returncode, _ps_timeout = run_with_timeout(
                    ["ps", "-eo", "pid=,comm=,args="],
                    8,
                    env,
                    args.cwd,
                )
                ps_text = ps_stdout + ps_stderr
                ps_log.write_text(ps_text, encoding="utf-8", errors="replace")
                linux_pid = parse_lolg95_linux_pid(ps_text, args.runtime_executable.name)
                if not linux_pid:
                    force_level_write_status = "missing_linux_pid"
                    issues.append("missing_lolg95_linux_process")
                    force_level_log.write_text("", encoding="utf-8")
                else:
                    writes = []
                    if args.force_level_index is not None:
                        writes.append((0x005B0948, args.force_level_index))
                    if args.force_level_slot is not None:
                        writes.append((0x005B094C, args.force_level_slot))
                    force_log_text, force_issues = write_process_dwords(linux_pid, writes)
                    force_level_log.write_text(force_log_text, encoding="utf-8", errors="replace")
                    if force_issues:
                        force_level_write_status = "failed"
                        issues.extend(force_issues)
                    else:
                        force_level_write_status = "pass"
            if not attach_pid:
                issues.append("missing_lolg95_process")
                raw_log.write_text("", encoding="utf-8")
            else:
                build_attach_command_file(command_file, attach_pid, tracepoints, args.capture_stops)
                winedbg_command = [winedbg or "winedbg", "--file", str(command_file)]
                with raw_log.open("w", encoding="utf-8", errors="replace") as raw_handle:
                    debugger = subprocess.Popen(
                        winedbg_command,
                        stdout=raw_handle,
                        stderr=subprocess.STDOUT,
                        text=True,
                        env=env,
                        cwd=args.cwd,
                    )
                    time.sleep(args.click_delay)
                    if args.click:
                        click_command = [
                            xdotool or "xdotool",
                            "search",
                            "--name",
                            args.click_window_name,
                            "mousemove",
                            "--window",
                            "%@",
                            str(args.click_x),
                            str(args.click_y),
                            "click",
                            "1",
                        ]
                        click_results = []
                        for _index in range(args.click_count):
                            click_stdout, click_stderr, click_returncode, click_timeout = run_with_timeout(
                                click_command,
                                args.click_timeout,
                                env,
                                args.cwd,
                            )
                            click_results.append(
                                f"returncode={click_returncode or 'timeout'} timeout={click_timeout}\n"
                                f"{click_stdout}{click_stderr}"
                            )
                            if args.click_interval:
                                time.sleep(args.click_interval)
                        xdotool_log.write_text("\n--- click ---\n".join(click_results), encoding="utf-8")
                        xdotool_status = ";".join(line.splitlines()[0] for line in click_results)
                    if args.pilot_key and xdotool:
                        key_results = []
                        for key_name in args.pilot_key:
                            if args.pilot_key_delay:
                                time.sleep(args.pilot_key_delay)
                            key_command = [
                                xdotool,
                                "search",
                                "--name",
                                args.click_window_name,
                                "key",
                                "--window",
                                "%@",
                                key_name,
                            ]
                            key_stdout, key_stderr, key_returncode, key_timeout = run_with_timeout(
                                key_command,
                                args.click_timeout,
                                env,
                                args.cwd,
                            )
                            key_results.append(
                                f"key={key_name} returncode={key_returncode or 'timeout'} timeout={key_timeout}\n"
                                f"{key_stdout}{key_stderr}"
                            )
                        pilot_key_log.write_text("\n--- key ---\n".join(key_results), encoding="utf-8")
                        pilot_key_status = ";".join(line.splitlines()[0] for line in key_results)
                    try:
                        winedbg_returncode = str(debugger.wait(timeout=args.attach_timeout))
                        session_status = "exited_0" if winedbg_returncode == "0" else f"exited_{winedbg_returncode}"
                    except subprocess.TimeoutExpired:
                        winedbg_timed_out = "1"
                        session_status = "started_timeout"
                        debugger.kill()
                        debugger.wait(timeout=8)
                if xwininfo:
                    xwin_stdout, xwin_stderr, _xwin_returncode, _xwin_timeout = run_with_timeout(
                        [xwininfo, "-root", "-tree"],
                        8,
                        env,
                        args.cwd,
                    )
                    xwininfo_log.write_text(xwin_stdout + xwin_stderr, encoding="utf-8", errors="replace")
        finally:
            stop_process(game_process)

    raw_text = raw_log.read_text(encoding="utf-8", errors="replace") if raw_log.exists() else ""
    trace_rows, breakpoint_hits, invalid_breakpoints, incomplete_hits = extract_trace_rows(raw_text, tracepoints)
    write_csv(trace_path, TRACE_FIELDS, trace_rows, delimiter="\t")
    if incomplete_hits:
        issues.append(f"incomplete_breakpoint_hits:{incomplete_hits}")
    if invalid_breakpoints:
        issues.append(f"invalid_breakpoints:{invalid_breakpoints}")
    if breakpoint_hits == 0:
        issues.append("no_contract_breakpoint_hits")
    if not trace_rows:
        issues.append("no_trace_rows")

    createfile_hits = sum(1 for row in trace_rows if row.get("kind") == "createfile")
    mix_constructor_hits = sum(1 for row in trace_rows if row.get("kind") == "mix_constructor")
    captured_paths = [row.get("path_ascii", "") for row in trace_rows if row.get("path_ascii", "")]
    raw_upper = raw_text.upper()
    l20_bbi_mentions = raw_upper.count("L20_BBI")
    l20_bbi_hd_mentions = raw_upper.count("L20_BBI_HD")
    if l20_bbi_hd_mentions:
        status = "pass"
        next_step = "confirm the HD sidecar archive path is loaded after the gameplay transition"
    elif l20_bbi_mentions:
        status = "gap"
        next_step = "add or validate the L20_BBI_HD.MIX fallback at the captured loader call site"
    elif trace_rows:
        status = "gap"
        next_step = "drive gameplay further after the first menu transition until L20_BBI.MIX is observed"
    else:
        status = "gap"
        next_step = "check attach timing and pilot input because no loader breakpoints were captured"

    summary = {
        "status": status,
        "session_status": session_status,
        "tracepoints": str(args.tracepoints),
        "runtime_executable": str(args.runtime_executable),
        "runtime_args": shlex.join(runtime_args),
        "wineprefix": str(args.wineprefix),
        "wine_desktop": args.wine_desktop,
        "startup_wait_seconds": str(args.startup_wait),
        "attach_pid": attach_pid,
        "linux_pid": linux_pid,
        "force_level_index": "" if args.force_level_index is None else str(args.force_level_index),
        "force_level_slot": "" if args.force_level_slot is None else str(args.force_level_slot),
        "force_level_write_status": force_level_write_status,
        "force_level_write_log": str(force_level_log) if force_level_write_status else "",
        "command": shlex.join(game_command),
        "winedbg_command": shlex.join([winedbg or "winedbg", "--file", str(command_file)]),
        "winedbg_returncode": winedbg_returncode,
        "winedbg_timed_out": winedbg_timed_out,
        "xdotool_command": (
            shlex.join(
                [
                    xdotool or "xdotool",
                    "search",
                    "--name",
                    args.click_window_name,
                    "mousemove",
                    "--window",
                    "%@",
                    str(args.click_x),
                    str(args.click_y),
                    "click",
                    "1",
                ]
            )
            if args.click
            else ""
        ),
        "xdotool_status": xdotool_status,
        "pilot_keys": " ".join(args.pilot_key),
        "pilot_key_status": pilot_key_status,
        "command_file": str(command_file),
        "info_proc_log": str(info_proc_log),
        "raw_log": str(raw_log),
        "trace": str(trace_path),
        "capture_stops": str(args.capture_stops),
        "contract_tracepoints": str(len(tracepoints)),
        "breakpoint_hits": str(breakpoint_hits),
        "invalid_breakpoints": str(invalid_breakpoints),
        "extracted_rows": str(len(trace_rows)),
        "createfile_hits": str(createfile_hits),
        "mix_constructor_hits": str(mix_constructor_hits),
        "path_rows": str(len(captured_paths)),
        "unique_paths": str(len({path.lower() for path in captured_paths})),
        "l20_bbi_mentions": str(l20_bbi_mentions),
        "l20_bbi_hd_mentions": str(l20_bbi_hd_mentions),
        "issues": ";".join(dict.fromkeys(issues)),
        "next_step": next_step,
    }
    write_csv(output / "summary.csv", SUMMARY_FIELDS, [summary])
    return summary


def main() -> None:
    parser = argparse.ArgumentParser(description="Attach winedbg to the visible LOLG95 Wine process and pilot the menu.")
    parser.add_argument("--tracepoints", type=Path, default=DEFAULT_TRACEPOINTS)
    parser.add_argument("-o", "--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--runtime-executable", type=Path, default=Path("LOLG95.EXE"))
    parser.add_argument("--runtime-arg", action="append", default=[])
    parser.add_argument("--cwd", type=Path, default=Path.cwd())
    parser.add_argument("--wineprefix", type=Path, required=True)
    parser.add_argument("--wine", default="")
    parser.add_argument("--winedbg", default="")
    parser.add_argument("--winedebug", default="-all")
    parser.add_argument("--wine-desktop", default="LOLG,1280x1024")
    parser.add_argument("--startup-wait", type=int, default=35)
    parser.add_argument("--info-timeout", type=int, default=12)
    parser.add_argument("--attach-timeout", type=int, default=100)
    parser.add_argument("--capture-stops", type=int, default=256)
    parser.add_argument("--xwininfo", default="")
    parser.add_argument("--xdotool", default="/tmp/xdotool-local/usr/bin/xdotool")
    parser.add_argument("--xdotool-library-path", default="/tmp/xdotool-local/usr/lib/x86_64-linux-gnu")
    parser.add_argument("--click", action=argparse.BooleanOptionalAction, default=True)
    parser.add_argument("--click-window-name", default="Lands Of Lore Guardians")
    parser.add_argument("--click-x", type=int, default=95)
    parser.add_argument("--click-y", type=int, default=116)
    parser.add_argument("--click-delay", type=int, default=6)
    parser.add_argument("--click-timeout", type=int, default=8)
    parser.add_argument("--click-count", type=int, default=2)
    parser.add_argument("--click-interval", type=float, default=2.0)
    parser.add_argument("--pilot-key", action="append", default=[])
    parser.add_argument("--pilot-key-delay", type=float, default=8.0)
    parser.add_argument("--force-level-index", type=lambda value: int(value, 0))
    parser.add_argument("--force-level-slot", type=lambda value: int(value, 0))
    args = parser.parse_args()

    summary = run_attempt(args)
    print(f"LOLG95 attached pilot trace: {summary['status']} ({summary['session_status']})")
    print(f"Summary: {args.output / 'summary.csv'}")
    print(f"Trace rows: {summary['extracted_rows']} / hits: {summary['breakpoint_hits']}")
    print(f"Attach PID: {summary['attach_pid'] or 'not found'}")


if __name__ == "__main__":
    main()
