#!/usr/bin/env python3
"""Trace LOLG95 sidecar file seeks/reads in a visible Wine process."""

from __future__ import annotations

import argparse
import csv
import html
import json
import os
import re
import shlex
import shutil
import subprocess
import sys
import time
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from run_lolg95_winedbg_attach_pilot_attempt import (  # noqa: E402
    parse_lolg95_linux_pid,
    parse_lolg95_pid,
    run_with_timeout,
    stop_process,
    write_process_dwords,
)
from run_lolg95_runtime_archive_list_probe import (  # noqa: E402
    ARCHIVE_FIELDS,
    DEFAULT_EXPECTED_IDS,
    TARGET_FIELDS as ARCHIVE_TARGET_FIELDS,
    load_expected,
    scan_archive_list,
)


DEFAULT_OUTPUT = Path("output/lolg95_sidecar_file_io_trace_attempt")
DEFAULT_TRACEPOINTS = Path("output/lolg95_sidecar_file_io_trace_contract/tracepoints.tsv")
DEFAULT_TARGETS = Path("output/lolg95_sidecar_file_io_trace_contract/targets.csv")

TRACE_FIELDS = [
    "row_index",
    "breakpoint_va",
    "kind",
    "path",
    "path_pointer",
    "archive_pointer_role",
    "archive_name",
    "file_object",
    "file_object_word",
    "file_handle",
    "edi",
    "esi",
    "esp0",
    "esp4",
    "esp8",
    "esp12",
    "esp16",
    "seek_offset",
    "seek_method",
    "read_size",
    "target_status",
    "target_file_id",
    "target_index",
    "target_range_start",
    "target_range_end",
    "notes",
]

SUMMARY_FIELDS = [
    "status",
    "session_status",
    "tracepoints",
    "targets",
    "runtime_executable",
    "runtime_args",
    "wineprefix",
    "wine_desktop",
    "startup_wait_seconds",
    "attach_pid",
    "attach_pid_source",
    "linux_pid",
    "force_level_index",
    "force_level_slot",
    "force_level_write_status",
    "force_level_write_log",
    "command",
    "winedbg_command",
    "winedbg_returncode",
    "winedbg_timed_out",
    "xdotool_command",
    "xdotool_status",
    "pilot_keys",
    "pilot_key_status",
    "command_file",
    "info_proc_log",
    "raw_log",
    "trace",
    "archives",
    "archive_targets",
    "archive_scan_phase",
    "capture_stops",
    "archive_nodes",
    "archive_names",
    "runtime_sidecar_first",
    "runtime_base_first",
    "runtime_missing",
    "runtime_unknown_first",
    "breakpoint_hits",
    "setfilepointer_hits",
    "readfile_hits",
    "sidecar_path_hits",
    "archive_pointer_mapped_hits",
    "sidecar_archive_pointer_hits",
    "target_offset_seek_hits",
    "unmapped_target_offset_seek_hits",
    "target_seek_hits",
    "target_read_hits",
    "target_ids_seen",
    "target_read_ids_seen",
    "issues",
    "next_step",
]


def read_csv(path: Path, delimiter: str = ",") -> list[dict[str, str]]:
    if not path.exists():
        return []
    with path.open(newline="", encoding="utf-8") as handle:
        return list(csv.DictReader(handle, delimiter=delimiter))


def write_csv(path: Path, fieldnames: list[str], rows: list[dict[str, str]], delimiter: str = ",") -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames, delimiter=delimiter)
        writer.writeheader()
        writer.writerows(rows)


def parse_hex(text: str) -> int:
    value = text.strip().lower()
    if value.startswith("0x"):
        return int(value, 16)
    return int(value, 16)


def hex32(value: int) -> str:
    return f"0x{value & 0xFFFFFFFF:08x}"


def value_to_int(value: str) -> int:
    text = str(value).strip()
    if not text:
        return 0
    if text.lower().startswith("0x"):
        return int(text, 16)
    return int(text)


def load_targets(path: Path) -> list[dict[str, str]]:
    rows = read_csv(path)
    rows.sort(key=lambda row: value_to_int(row.get("expected_file_offset_start", "0")))
    return rows


def target_for_offset(targets: list[dict[str, str]], offset: int) -> dict[str, str]:
    for row in targets:
        start = value_to_int(row.get("expected_file_offset_start", "0"))
        end = value_to_int(row.get("expected_file_offset_end", "0"))
        if start <= offset < end:
            return row
    return {}


def build_command_file(path: Path, attach_pid: str, tracepoints: list[dict[str, str]], capture_stops: int) -> None:
    lines = [
        "# Generated by tools/run_lolg95_sidecar_file_io_trace_attempt.py",
        f"attach 0x{attach_pid}",
    ]
    for row in tracepoints:
        lines.append(f"break *{row['breakpoint_va']}")
    for _index in range(capture_stops):
        lines.extend(
            [
                "cont",
                "info regs",
                "x /x $ebx",
                "x /x ($ebx + 0x10)",
                "x /x ($ebx + 0x18)",
                "x /x $edi",
                "x /x $esi",
                "x /x $esp",
                "x /x ($esp + 4)",
                "x /x ($esp + 8)",
                "x /x ($esp + 12)",
                "x /x ($esp + 16)",
                "x /s *($ebx + 0x18)",
                "x /s *(int*)($ebx + 0x18)",
                "x /s *((int*)($ebx + 0x18))",
                "x /s *(char**)($ebx + 0x18)",
                "x /s *((char**)($ebx + 0x18))",
            ]
        )
    lines.append("quit")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def parse_registers(block: str) -> dict[str, str]:
    registers: dict[str, str] = {}
    for source, target in {
        "EIP": "eip",
        "EBX": "ebx",
        "EDI": "edi",
        "ESI": "esi",
        "ESP": "esp",
    }.items():
        match = re.search(rf"\b{source}:([0-9a-fA-F]{{8,16}})\b", block)
        if match:
            registers[target] = hex32(parse_hex(match.group(1)))
    return registers


def parse_path_hint(block: str) -> str:
    for line in block.splitlines():
        if ".MIX" not in line.upper():
            continue
        text = line.strip()
        quoted = re.search(r'"([^"]*\.MIX[^"]*)"', text, flags=re.IGNORECASE)
        if quoted:
            return quoted.group(1)
        if ":" in text:
            text = text.split(":", 1)[1].strip()
        return text.strip().strip('"')
    return ""


def isolated_values(block: str) -> list[str]:
    return [hex32(parse_hex(value)) for value in re.findall(r"^\s*([0-9a-fA-F]{8})\s*$", block, re.MULTILINE)]


def sidecar_path(path: str) -> bool:
    return "l20_bbi_hd.mix" in path.replace("\\", "/").lower()


def parse_attach_pid(info_proc_text: str, executable_name: str) -> tuple[str, str]:
    direct_pid = parse_lolg95_pid(info_proc_text, executable_name)
    if direct_pid:
        return direct_pid, "runtime_executable"

    explorer_pids = []
    for line in info_proc_text.splitlines():
        match = re.search(r"^\s*=?([0-9a-fA-F]{8})\s+\d+\s+.*'explorer\.exe'", line, re.IGNORECASE)
        if match:
            explorer_pids.append(match.group(1).lower())
    if explorer_pids:
        return explorer_pids[-1], "explorer_fallback"
    return "", ""


def runtime_command_path(runtime_executable: Path, cwd: Path) -> str:
    return str(runtime_executable.resolve())


def normalize_pointer(value: str) -> str:
    try:
        return hex32(value_to_int(value))
    except ValueError:
        return ""


def build_archive_pointer_map(archive_rows: list[dict[str, str]]) -> dict[str, dict[str, str]]:
    pointer_map: dict[str, dict[str, str]] = {}
    for row in archive_rows:
        name = row.get("name", "")
        if not name:
            continue
        for field, role in [
            ("node", "node"),
            ("name_pointer", "name_pointer"),
            ("table_pointer", "table_pointer"),
            ("body_pointer", "body_pointer"),
        ]:
            pointer = normalize_pointer(row.get(field, ""))
            if pointer and pointer != "0x00000000":
                pointer_map[pointer] = {"archive_name": name, "archive_pointer_role": role}
    return pointer_map


def classify_rows(rows: list[dict[str, str]], targets: list[dict[str, str]]) -> None:
    last_sidecar_target: dict[str, str] = {}
    for row in rows:
        path_is_sidecar = sidecar_path(row["path"]) or sidecar_path(row.get("archive_name", ""))
        if row["kind"] == "SetFilePointer":
            offset = value_to_int(row["seek_offset"])
            target = target_for_offset(targets, offset)
            if path_is_sidecar and target:
                row["target_status"] = "sidecar_target_seek"
                row["target_file_id"] = target.get("file_id", "")
                row["target_index"] = target.get("index", "")
                row["target_range_start"] = target.get("expected_file_offset_start", "")
                row["target_range_end"] = target.get("expected_file_offset_end", "")
                last_sidecar_target = target
            elif target and not row["path"]:
                row["target_status"] = "target_offset_seek_unmapped_handle"
                row["target_file_id"] = target.get("file_id", "")
                row["target_index"] = target.get("index", "")
                row["target_range_start"] = target.get("expected_file_offset_start", "")
                row["target_range_end"] = target.get("expected_file_offset_end", "")
                row["notes"] = "offset matches a sidecar target range, but the archive path was not decoded"
            elif target:
                row["target_status"] = "non_sidecar_target_offset_seek"
                row["target_file_id"] = target.get("file_id", "")
                row["target_index"] = target.get("index", "")
                row["target_range_start"] = target.get("expected_file_offset_start", "")
                row["target_range_end"] = target.get("expected_file_offset_end", "")
                row["notes"] = "offset matches a target range on a non-sidecar path"
            elif path_is_sidecar:
                row["target_status"] = "sidecar_non_target_seek"
            else:
                row["target_status"] = "non_sidecar_seek"
        elif row["kind"] == "ReadFile":
            if path_is_sidecar and last_sidecar_target:
                row["target_status"] = "sidecar_target_read_after_seek"
                row["target_file_id"] = last_sidecar_target.get("file_id", "")
                row["target_index"] = last_sidecar_target.get("index", "")
                row["target_range_start"] = last_sidecar_target.get("expected_file_offset_start", "")
                row["target_range_end"] = last_sidecar_target.get("expected_file_offset_end", "")
            elif path_is_sidecar:
                row["target_status"] = "sidecar_read_without_target_seek"
            else:
                row["target_status"] = "non_sidecar_read"


def extract_trace_rows(
    raw_text: str,
    tracepoints: list[dict[str, str]],
    targets: list[dict[str, str]],
    archive_pointer_map: dict[str, dict[str, str]],
) -> tuple[list[dict[str, str]], int]:
    tracepoint_by_va = {hex32(value_to_int(row["breakpoint_va"])): row for row in tracepoints}
    stop_re = re.compile(r"Stopped on breakpoint\s+\d+\s+at\s+(0x[0-9a-fA-F]+)", re.IGNORECASE)
    matches = list(stop_re.finditer(raw_text))
    rows: list[dict[str, str]] = []
    breakpoint_hits = 0
    for index, match in enumerate(matches):
        breakpoint_va = hex32(parse_hex(match.group(1)))
        tracepoint = tracepoint_by_va.get(breakpoint_va)
        block_end = matches[index + 1].start() if index + 1 < len(matches) else len(raw_text)
        block = raw_text[match.start() : block_end]
        if not tracepoint:
            continue
        breakpoint_hits += 1
        registers = parse_registers(block)
        values = isolated_values(block)
        file_object = registers.get("ebx", "")
        file_object_word = values[0] if len(values) > 0 else ""
        file_handle = values[1] if len(values) > 1 else ""
        path_pointer = values[2] if len(values) > 2 else ""
        archive_pointer = archive_pointer_map.get(normalize_pointer(path_pointer), {})
        edi = values[3] if len(values) > 3 else registers.get("edi", "")
        esi = values[4] if len(values) > 4 else registers.get("esi", "")
        esp0 = values[5] if len(values) > 5 else ""
        esp4 = values[6] if len(values) > 6 else ""
        esp8 = values[7] if len(values) > 7 else ""
        esp12 = values[8] if len(values) > 8 else ""
        esp16 = values[9] if len(values) > 9 else ""
        kind = tracepoint.get("kind", "")
        rows.append(
            {
                "row_index": str(len(rows)),
                "breakpoint_va": breakpoint_va,
                "kind": kind,
                "path": parse_path_hint(block) or archive_pointer.get("archive_name", ""),
                "path_pointer": path_pointer,
                "archive_pointer_role": archive_pointer.get("archive_pointer_role", ""),
                "archive_name": archive_pointer.get("archive_name", ""),
                "file_object": file_object,
                "file_object_word": file_object_word,
                "file_handle": file_handle,
                "edi": edi,
                "esi": esi,
                "esp0": esp0,
                "esp4": esp4,
                "esp8": esp8,
                "esp12": esp12,
                "esp16": esp16,
                "seek_offset": edi if kind == "SetFilePointer" else "",
                "seek_method": esi if kind == "SetFilePointer" else "",
                "read_size": esp8 if kind == "ReadFile" else "",
                "target_status": "",
                "target_file_id": "",
                "target_index": "",
                "target_range_start": "",
                "target_range_end": "",
                "notes": "",
            }
        )
    classify_rows(rows, targets)
    return rows, breakpoint_hits


def render_table(rows: list[dict[str, str]], fields: list[str]) -> str:
    head = "".join(f"<th>{html.escape(field)}</th>" for field in fields)
    body = []
    for row in rows:
        body.append("<tr>" + "".join(f"<td>{html.escape(row.get(field, ''))}</td>" for field in fields) + "</tr>")
    return f"<table><thead><tr>{head}</tr></thead><tbody>{''.join(body)}</tbody></table>"


def write_html(path: Path, summary: dict[str, str], trace_rows: list[dict[str, str]]) -> None:
    payload = {"summary": summary, "trace": trace_rows}
    data_json = json.dumps(payload, ensure_ascii=True, separators=(",", ":"))
    page = f"""<!doctype html>
<html lang="fr">
<head>
  <meta charset="utf-8">
  <title>LOLG95 Sidecar File-I/O Trace Attempt</title>
  <style>
    body {{ font-family: system-ui, sans-serif; margin: 24px; background: #f7f7f3; color: #1f2933; }}
    h1, h2 {{ margin-bottom: 0.4rem; }}
    .grid {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(180px, 1fr)); gap: 12px; }}
    .stat {{ background: white; border: 1px solid #d7d7ce; border-radius: 6px; padding: 12px; }}
    .label {{ color: #5f6b76; font-size: 0.85rem; }}
    .value {{ font-size: 1.35rem; font-weight: 700; }}
    table {{ border-collapse: collapse; width: 100%; background: white; margin: 12px 0 24px; }}
    th, td {{ border: 1px solid #d7d7ce; padding: 6px 8px; text-align: left; font-size: 0.86rem; }}
    th {{ background: #ecece4; }}
  </style>
</head>
<body>
  <h1>LOLG95 Sidecar File-I/O Trace Attempt</h1>
  <div class="grid">
    <div class="stat"><div class="label">Statut</div><div class="value">{html.escape(summary['status'])}</div></div>
    <div class="stat"><div class="label">Session</div><div class="value">{html.escape(summary['session_status'])}</div></div>
    <div class="stat"><div class="label">Sidecar paths</div><div class="value">{html.escape(summary['sidecar_path_hits'])}</div></div>
    <div class="stat"><div class="label">Target reads</div><div class="value">{html.escape(summary['target_read_hits'])}</div></div>
  </div>
  <h2>Synthese</h2>
  {render_table([summary], SUMMARY_FIELDS)}
  <h2>Trace</h2>
  {render_table(trace_rows, TRACE_FIELDS)}
  <script type="application/json" id="lolg95-sidecar-file-io-trace-attempt">{html.escape(data_json)}</script>
</body>
</html>
"""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(page, encoding="utf-8")


def run_attempt(args: argparse.Namespace) -> dict[str, str]:
    output = args.output.resolve()
    output.mkdir(parents=True, exist_ok=True)
    info_proc_log = output / "info_proc.log"
    raw_log = output / "raw.log"
    trace_path = output / "trace.tsv"
    archives_path = output / "archives.tsv"
    archive_targets_path = output / "archive_targets.tsv"
    command_file = output / "winedbg_file_io_commands.txt"
    xdotool_log = output / "xdotool.log"
    pilot_key_log = output / "pilot_keys.log"
    ps_log = output / "ps.txt"
    force_level_log = output / "force_level_write.log"
    game_stdout = output / "game.out"
    game_stderr = output / "game.err"

    tracepoints = read_csv(args.tracepoints, delimiter="\t")
    targets = load_targets(args.targets)
    expected = load_expected(args.expected_ids)
    issues: list[str] = []
    if not tracepoints:
        issues.append("missing_tracepoints")
    if not targets:
        issues.append("missing_targets")
    if not expected:
        issues.append("missing_expected_ids")

    wine = args.wine or shutil.which("wine") or ""
    winedbg = args.winedbg or shutil.which("winedbg") or ""
    xdotool = args.xdotool or shutil.which("xdotool") or ""
    if not wine:
        issues.append("missing_wine")
    if not winedbg:
        issues.append("missing_winedbg")
    if not args.runtime_executable.is_file():
        issues.append("missing_runtime_executable")
    if args.click and not xdotool:
        issues.append("missing_xdotool")

    env = os.environ.copy()
    env["WINEPREFIX"] = str(args.wineprefix.resolve())
    env["WINEDEBUG"] = args.winedebug
    if args.xdotool_library_path:
        env["LD_LIBRARY_PATH"] = (
            args.xdotool_library_path
            if not env.get("LD_LIBRARY_PATH")
            else f"{args.xdotool_library_path}:{env['LD_LIBRARY_PATH']}"
        )

    runtime_args = args.runtime_arg or ["-CD", r"D:\WESTWOOD\LOLG"]
    runtime_command = args.runtime_command or runtime_command_path(args.runtime_executable, args.cwd)
    if args.direct:
        game_command = [wine or "wine", runtime_command, *runtime_args]
    else:
        game_command = [
            wine or "wine",
            "explorer",
            f"/desktop={args.wine_desktop}",
            runtime_command,
            *runtime_args,
        ]
    session_status = "dry_run" if args.dry_run else "not_started"
    attach_pid = ""
    attach_pid_source = ""
    linux_pid = ""
    force_level_write_status = ""
    xdotool_status = ""
    pilot_key_status = ""
    winedbg_returncode = ""
    winedbg_timed_out = "0"
    game_process: subprocess.Popen[str] | None = None
    archive_rows: list[dict[str, str]] = []
    archive_target_rows: list[dict[str, str]] = []
    archive_scan_phase = ""

    def refresh_archive_scan(phase: str) -> None:
        nonlocal archive_rows, archive_target_rows, archive_scan_phase
        if not linux_pid:
            issues.append(f"missing_runtime_memory_probe_pid:{phase}")
            return
        rows, target_rows, scan_issues = scan_archive_list(linux_pid, expected, args.max_archives)
        if rows:
            archive_rows = rows
            archive_target_rows = target_rows
            archive_scan_phase = phase
        issues.extend(f"archive_scan:{phase}:{issue}" for issue in scan_issues)
        write_csv(archives_path, ARCHIVE_FIELDS, archive_rows, delimiter="\t")
        write_csv(archive_targets_path, ARCHIVE_TARGET_FIELDS, archive_target_rows, delimiter="\t")

    if args.dry_run:
        build_command_file(command_file, "00000000", tracepoints, args.capture_stops)
        raw_log.write_text("", encoding="utf-8")
        info_proc_log.write_text("", encoding="utf-8")
        write_csv(archives_path, ARCHIVE_FIELDS, archive_rows, delimiter="\t")
        write_csv(archive_targets_path, ARCHIVE_TARGET_FIELDS, archive_target_rows, delimiter="\t")
        if args.force_level_index is not None or args.force_level_slot is not None:
            planned_writes = []
            if args.force_level_index is not None:
                planned_writes.append(f"0x005b0948={args.force_level_index}")
            if args.force_level_slot is not None:
                planned_writes.append(f"0x005b094c={args.force_level_slot}")
            force_level_write_status = "dry_run"
            force_level_log.write_text("dry_run " + " ".join(planned_writes) + "\n", encoding="utf-8")
        else:
            force_level_log.write_text("", encoding="utf-8")
    elif any(issue.startswith("missing_") for issue in issues):
        raw_log.write_text("", encoding="utf-8")
        info_proc_log.write_text("", encoding="utf-8")
        force_level_log.write_text("", encoding="utf-8")
        write_csv(archives_path, ARCHIVE_FIELDS, archive_rows, delimiter="\t")
        write_csv(archive_targets_path, ARCHIVE_TARGET_FIELDS, archive_target_rows, delimiter="\t")
    else:
        try:
            with game_stdout.open("w", encoding="utf-8", errors="replace") as stdout_handle, game_stderr.open(
                "w", encoding="utf-8", errors="replace"
            ) as stderr_handle:
                game_process = subprocess.Popen(
                    game_command,
                    stdout=stdout_handle,
                    stderr=stderr_handle,
                    text=True,
                    env=env,
                    cwd=args.cwd,
                )
            time.sleep(args.startup_wait)
            info_stdout, info_stderr, _info_returncode, _info_timeout = run_with_timeout(
                [winedbg or "winedbg", "--command", "info proc"],
                args.info_timeout,
                env,
                args.cwd,
            )
            info_proc_text = info_stdout + info_stderr
            info_proc_log.write_text(info_proc_text, encoding="utf-8", errors="replace")
            attach_pid, attach_pid_source = parse_attach_pid(info_proc_text, args.runtime_executable.name)

            if args.force_level_index is not None or args.force_level_slot is not None:
                ps_stdout, ps_stderr, _ps_returncode, _ps_timeout = run_with_timeout(
                    ["ps", "-eo", "pid=,comm=,args="],
                    8,
                    env,
                    args.cwd,
                )
                ps_text = ps_stdout + ps_stderr
                ps_log.write_text(ps_text, encoding="utf-8", errors="replace")
                linux_pid = parse_lolg95_linux_pid(ps_text, args.runtime_executable.name)
                if not linux_pid:
                    force_level_write_status = "missing_linux_pid"
                    issues.append("missing_lolg95_linux_process")
                    force_level_log.write_text("", encoding="utf-8")
                else:
                    writes = []
                    if args.force_level_index is not None:
                        writes.append((0x005B0948, args.force_level_index))
                    if args.force_level_slot is not None:
                        writes.append((0x005B094C, args.force_level_slot))
                    force_log_text, force_issues = write_process_dwords(linux_pid, writes)
                    force_level_log.write_text(force_log_text, encoding="utf-8", errors="replace")
                    if force_issues:
                        force_level_write_status = "failed"
                        issues.extend(force_issues)
                    else:
                        force_level_write_status = "pass"

            refresh_archive_scan("pre_debug")

            if not attach_pid:
                issues.append("missing_lolg95_process")
                raw_log.write_text("", encoding="utf-8")
            else:
                build_command_file(command_file, attach_pid, tracepoints, args.capture_stops)
                winedbg_command = [winedbg or "winedbg", "--file", str(command_file)]
                with raw_log.open("w", encoding="utf-8", errors="replace") as raw_handle:
                    debugger = subprocess.Popen(
                        winedbg_command,
                        stdout=raw_handle,
                        stderr=subprocess.STDOUT,
                        text=True,
                        env=env,
                        cwd=args.cwd,
                    )
                    time.sleep(args.click_delay)
                    if args.click:
                        click_command = [
                            xdotool or "xdotool",
                            "search",
                            "--name",
                            args.click_window_name,
                            "mousemove",
                            "--window",
                            "%@",
                            str(args.click_x),
                            str(args.click_y),
                            "click",
                            "1",
                        ]
                        click_results = []
                        for _index in range(args.click_count):
                            click_stdout, click_stderr, click_returncode, click_timeout = run_with_timeout(
                                click_command,
                                args.click_timeout,
                                env,
                                args.cwd,
                            )
                            click_results.append(
                                f"returncode={click_returncode or 'timeout'} timeout={click_timeout}\n"
                                f"{click_stdout}{click_stderr}"
                            )
                            if args.click_interval:
                                time.sleep(args.click_interval)
                        xdotool_log.write_text("\n--- click ---\n".join(click_results), encoding="utf-8")
                        xdotool_status = ";".join(line.splitlines()[0] for line in click_results)
                    if args.pilot_key and xdotool:
                        key_results = []
                        for key_name in args.pilot_key:
                            if args.pilot_key_delay:
                                time.sleep(args.pilot_key_delay)
                            key_command = [
                                xdotool,
                                "search",
                                "--name",
                                args.click_window_name,
                                "key",
                                "--window",
                                "%@",
                                key_name,
                            ]
                            key_stdout, key_stderr, key_returncode, key_timeout = run_with_timeout(
                                key_command,
                                args.click_timeout,
                                env,
                                args.cwd,
                            )
                            key_results.append(
                                f"key={key_name} returncode={key_returncode or 'timeout'} timeout={key_timeout}\n"
                                f"{key_stdout}{key_stderr}"
                            )
                        pilot_key_log.write_text("\n--- key ---\n".join(key_results), encoding="utf-8")
                        pilot_key_status = ";".join(line.splitlines()[0] for line in key_results)
                    try:
                        winedbg_returncode = str(debugger.wait(timeout=args.attach_timeout))
                        session_status = "exited_0" if winedbg_returncode == "0" else f"exited_{winedbg_returncode}"
                    except subprocess.TimeoutExpired:
                        winedbg_timed_out = "1"
                        session_status = "started_timeout"
                        debugger.kill()
                        debugger.wait(timeout=8)
                if args.post_debug_archive_wait:
                    time.sleep(args.post_debug_archive_wait)
                refresh_archive_scan("post_debug")
        finally:
            stop_process(game_process)

    raw_text = raw_log.read_text(encoding="utf-8", errors="replace") if raw_log.exists() else ""
    archive_pointer_map = build_archive_pointer_map(archive_rows)
    trace_rows, breakpoint_hits = extract_trace_rows(raw_text, tracepoints, targets, archive_pointer_map)
    write_csv(trace_path, TRACE_FIELDS, trace_rows, delimiter="\t")
    if breakpoint_hits == 0 and not args.dry_run:
        issues.append("no_file_io_breakpoints")
    if not trace_rows and not args.dry_run:
        issues.append("no_file_io_trace_rows")

    setfilepointer_rows = [row for row in trace_rows if row["kind"] == "SetFilePointer"]
    readfile_rows = [row for row in trace_rows if row["kind"] == "ReadFile"]
    sidecar_path_rows = [row for row in trace_rows if sidecar_path(row["path"])]
    archive_pointer_mapped_rows = [row for row in trace_rows if row["archive_name"]]
    sidecar_archive_pointer_rows = [row for row in archive_pointer_mapped_rows if sidecar_path(row["archive_name"])]
    target_offset_seek_rows = [
        row
        for row in trace_rows
        if row["target_status"]
        in {"sidecar_target_seek", "target_offset_seek_unmapped_handle", "non_sidecar_target_offset_seek"}
    ]
    unmapped_target_offset_seek_rows = [
        row for row in trace_rows if row["target_status"] == "target_offset_seek_unmapped_handle"
    ]
    target_seek_rows = [row for row in trace_rows if row["target_status"] == "sidecar_target_seek"]
    target_read_rows = [row for row in trace_rows if row["target_status"] == "sidecar_target_read_after_seek"]
    target_ids_seen = sorted({row["target_file_id"] for row in target_seek_rows if row["target_file_id"]})
    target_read_ids_seen = sorted({row["target_file_id"] for row in target_read_rows if row["target_file_id"]})
    runtime_sidecar_first = [
        row["file_id"] for row in archive_target_rows if row.get("first_status") == "sidecar"
    ]
    runtime_base_first = [row["file_id"] for row in archive_target_rows if row.get("first_status") == "base"]
    runtime_missing = [row["file_id"] for row in archive_target_rows if row.get("first_status") == "missing"]
    runtime_unknown_first = [
        row["file_id"] for row in archive_target_rows if row.get("first_status") == "unknown_size"
    ]

    if target_read_rows:
        status = "pass"
        next_step = "confirm visual output for the read VQA and promote the sidecar runtime path"
    elif target_seek_rows:
        status = "gap"
        next_step = "extend capture until ReadFile follows the observed target sidecar seek"
    elif runtime_base_first:
        status = "gap"
        next_step = "change sidecar insertion order so duplicate VQA IDs are found before l20_bbI.MIX"
    elif sidecar_path_rows:
        status = "gap"
        next_step = "drive gameplay until a sidecar file seek falls inside one VQA target range"
    else:
        status = "gap"
        next_step = "drive gameplay or targeted VQA request until l20_bbI_HD.MIX file I/O is observed"

    command_file_text = str(command_file)
    summary = {
        "status": status,
        "session_status": session_status,
        "tracepoints": str(len(tracepoints)),
        "targets": str(len(targets)),
        "runtime_executable": str(args.runtime_executable),
        "runtime_args": shlex.join(runtime_args),
        "wineprefix": str(args.wineprefix),
        "wine_desktop": args.wine_desktop,
        "startup_wait_seconds": str(args.startup_wait),
        "attach_pid": attach_pid,
        "attach_pid_source": attach_pid_source,
        "linux_pid": linux_pid,
        "force_level_index": "" if args.force_level_index is None else str(args.force_level_index),
        "force_level_slot": "" if args.force_level_slot is None else str(args.force_level_slot),
        "force_level_write_status": force_level_write_status,
        "force_level_write_log": str(force_level_log) if force_level_write_status else "",
        "command": shlex.join(game_command),
        "winedbg_command": shlex.join([winedbg or "winedbg", "--file", command_file_text]),
        "winedbg_returncode": winedbg_returncode,
        "winedbg_timed_out": winedbg_timed_out,
        "xdotool_command": (
            shlex.join(
                [
                    xdotool or "xdotool",
                    "search",
                    "--name",
                    args.click_window_name,
                    "mousemove",
                    "--window",
                    "%@",
                    str(args.click_x),
                    str(args.click_y),
                    "click",
                    "1",
                ]
            )
            if args.click
            else ""
        ),
        "xdotool_status": xdotool_status,
        "pilot_keys": " ".join(args.pilot_key),
        "pilot_key_status": pilot_key_status,
        "command_file": command_file_text,
        "info_proc_log": str(info_proc_log),
        "raw_log": str(raw_log),
        "trace": str(trace_path),
        "archives": str(archives_path),
        "archive_targets": str(archive_targets_path),
        "archive_scan_phase": archive_scan_phase,
        "capture_stops": str(args.capture_stops),
        "archive_nodes": str(len(archive_rows)),
        "archive_names": ",".join(row["name"] for row in archive_rows if row.get("name")),
        "runtime_sidecar_first": ",".join(runtime_sidecar_first),
        "runtime_base_first": ",".join(runtime_base_first),
        "runtime_missing": ",".join(runtime_missing),
        "runtime_unknown_first": ",".join(runtime_unknown_first),
        "breakpoint_hits": str(breakpoint_hits),
        "setfilepointer_hits": str(len(setfilepointer_rows)),
        "readfile_hits": str(len(readfile_rows)),
        "sidecar_path_hits": str(len(sidecar_path_rows)),
        "archive_pointer_mapped_hits": str(len(archive_pointer_mapped_rows)),
        "sidecar_archive_pointer_hits": str(len(sidecar_archive_pointer_rows)),
        "target_offset_seek_hits": str(len(target_offset_seek_rows)),
        "unmapped_target_offset_seek_hits": str(len(unmapped_target_offset_seek_rows)),
        "target_seek_hits": str(len(target_seek_rows)),
        "target_read_hits": str(len(target_read_rows)),
        "target_ids_seen": ",".join(target_ids_seen),
        "target_read_ids_seen": ",".join(target_read_ids_seen),
        "issues": ";".join(dict.fromkeys(issues)),
        "next_step": next_step,
    }
    write_csv(output / "summary.csv", SUMMARY_FIELDS, [summary])
    write_html(output / "index.html", summary, trace_rows)
    return summary


def main() -> None:
    parser = argparse.ArgumentParser(description="Trace LOLG95 sidecar file seeks/reads under Wine/winedbg.")
    parser.add_argument("-o", "--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--tracepoints", type=Path, default=DEFAULT_TRACEPOINTS)
    parser.add_argument("--targets", type=Path, default=DEFAULT_TARGETS)
    parser.add_argument("--expected-ids", type=Path, default=DEFAULT_EXPECTED_IDS)
    parser.add_argument("--runtime-executable", type=Path, default=Path("LOLG95.EXE"))
    parser.add_argument("--runtime-command", default="")
    parser.add_argument("--runtime-arg", action="append", default=[])
    parser.add_argument("--cwd", type=Path, default=Path.cwd())
    parser.add_argument("--wineprefix", type=Path, required=True)
    parser.add_argument("--wine", default="")
    parser.add_argument("--winedbg", default="")
    parser.add_argument("--winedebug", default="-all")
    parser.add_argument("--wine-desktop", default="LOLG,1280x1024")
    parser.add_argument("--direct", action="store_true")
    parser.add_argument("--startup-wait", type=int, default=35)
    parser.add_argument("--info-timeout", type=int, default=12)
    parser.add_argument("--attach-timeout", type=int, default=120)
    parser.add_argument("--post-debug-archive-wait", type=int, default=8)
    parser.add_argument("--capture-stops", type=int, default=512)
    parser.add_argument("--xdotool", default="/tmp/xdotool-local/usr/bin/xdotool")
    parser.add_argument("--xdotool-library-path", default="/tmp/xdotool-local/usr/lib/x86_64-linux-gnu")
    parser.add_argument("--click", action=argparse.BooleanOptionalAction, default=True)
    parser.add_argument("--click-window-name", default="Lands Of Lore Guardians")
    parser.add_argument("--click-x", type=int, default=95)
    parser.add_argument("--click-y", type=int, default=116)
    parser.add_argument("--click-delay", type=int, default=6)
    parser.add_argument("--click-timeout", type=int, default=8)
    parser.add_argument("--click-count", type=int, default=2)
    parser.add_argument("--click-interval", type=float, default=2.0)
    parser.add_argument("--pilot-key", action="append", default=[])
    parser.add_argument("--pilot-key-delay", type=float, default=8.0)
    parser.add_argument("--force-level-index", type=lambda value: int(value, 0))
    parser.add_argument("--force-level-slot", type=lambda value: int(value, 0))
    parser.add_argument("--max-archives", type=int, default=128)
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()

    summary = run_attempt(args)
    print(f"LOLG95 sidecar file-I/O trace attempt: {summary['status']} ({summary['session_status']})")
    print(f"Summary: {args.output / 'summary.csv'}")
    print(
        "Sidecar target reads: "
        f"{summary['target_read_hits']} reads / {summary['target_seek_hits']} seeks / "
        f"{summary['sidecar_path_hits']} sidecar path hits"
    )


if __name__ == "__main__":
    main()
